"""add unique constraints for roles and permissions

Revision ID: b35f5ce93cf7
Revises: e31623ae8e30
Create Date: 2026-05-01 21:17:30.782573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b35f5ce93cf7'
down_revision: Union[str, Sequence[str], None] = 'e31623ae8e30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_role_permissions_role_module', 'role_permissions', ['role_id', 'module_id'])
    op.create_unique_constraint('uq_user_roles_user_id', 'user_roles', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_roles_user_id', 'user_roles', type_='unique')
    op.drop_constraint('uq_role_permissions_role_module', 'role_permissions', type_='unique')
    # ### end Alembic commands ###
